<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>JavSubtitleScraper</AssemblyName>
    <RootNamespace>JavSubtitleScraper</RootNamespace>
    <Version>1.0.1.0</Version>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MediaBrowser.Server.Core" Version="4.8.0.80-*" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Configuration.config.html" />
    <EmbeddedResource Include="Configuration.config.js" />
    <EmbeddedResource Include="thumb.png" />
  </ItemGroup>
</Project>
